### ISSUE TITLE
Compatibility with scikit-learn v. 0.20 (RandomizedPCA module was removed)

### ISSUE THREAD

**Issue by aron0093** [PMBio/f-scLVM#9]
I get the following error:

`Traceback (most recent call last):
  File "../../../scripts/slalom_AVM.py", line 2, in <module>
    import slalom
  File "/cluster/home/rgupta/miniconda3/lib/python3.6/site-packages/slalom/__init__.py", line 11, in <module>
    from .utils import (initFA, load_hdf5, load_txt, preTrain, plotLoadings, plotFactors, plotRelevance, saveFA, dumpFA)
  File "/cluster/home/rgupta/miniconda3/lib/python3.6/site-packages/slalom/utils.py", line 15, in <module>
    from sklearn.decomposition import RandomizedPCA,PCA
ImportError: cannot import name 'RandomizedPCA'`

As of version 0.20 the RandomizedPCA module has been removed from scikit-learn.

**Comment by mochar** [comment]
Looking at utils.py, the code does not even make use of RandomizedPCA so I just edited it out and it works fine now.

**Comment by spe301** [comment]
That worked for me. thank you!
